import React, { useEffect, useState } from 'react';
import { Workflow, Play, Pause, StepForward, RotateCcw, Minimize2, Check, X, Info, BookOpen } from 'lucide-react';
import { parseConstraint, examples } from './core/parser.js';
import { generateDFA, minimizeDFA, simulate } from './core/automata.js';
import Graph from './Graph.jsx';
const initial = generateDFA(parseConstraint(examples[0]));
export default function App() {
  const [prompt,setPrompt]=useState(examples[0]), [original,setOriginal]=useState(initial), [dfa,setDfa]=useState(initial);
  const [error,setError]=useState(''), [selected,setSelected]=useState('q0'), [layoutKey,setLayoutKey]=useState(0);
  const [input,setInput]=useState('110101'), [run,setRun]=useState(null), [cursor,setCursor]=useState(0), [playing,setPlaying]=useState(false), [testError,setTestError]=useState('');
  const [help,setHelp]=useState(false);
  useEffect(()=>{ if (!playing || !run) return; const timer=setInterval(()=>setCursor(c=>Math.min(c+1,run.steps.length-1)),650); return ()=>clearInterval(timer); },[playing,run]);
  useEffect(()=>{if(run && cursor===run.steps.length-1)setPlaying(false);},[cursor,run]);
  function clearRun(){setRun(null);setCursor(0);setPlaying(false);setTestError('');}
  function generate(e){e?.preventDefault();try{const next=generateDFA(parseConstraint(prompt));setOriginal(next);setDfa(next);setSelected(next.start);setError('');clearRun();}catch(err){setError(err.message);setPlaying(false);}}
  function startSimulation(e){e?.preventDefault();try{const result=simulate(dfa,input);setRun(result);setCursor(0);setPlaying(result.steps.length>1);setTestError('');}catch(err){clearRun();setTestError(err.message);}}
  function minimize(){const next=minimizeDFA(original);setDfa(next);setSelected(next.start);clearRun();}
  const c=dfa.constraint, state=dfa.states.find(s=>s.id===selected), active=run?.steps[cursor], done=run && cursor===run.steps.length-1;
  return <div className="app-shell">
    <a className="skip-link" href="#workspace">Skip to workspace</a><header className="topbar"><a className="brand" href="#"><span className="brand-icon"><Workflow size={23} aria-hidden="true"/></span>AutoMind <span className="brand-ai">AI</span></a><span className="course-label">Automata lab</span><button className="quiet" aria-expanded={help} aria-controls="pattern-guide" onClick={()=>setHelp(!help)}><BookOpen size={17} aria-hidden="true"/> Pattern guide</button></header>
    <main id="workspace">
      <div className="intro"><div><h1>From natural language to automata.</h1><p>Describe a language, explore its states, and follow a string through the machine.</p></div></div>
      {help && <section id="pattern-guide" className="guide panel"><h2>Supported pattern guide</h2><p>Use one condition per description. Binary is the default; a/b patterns infer {'{a, b}'}. Declare an alphabet with “Strings over {'{a,b}'} ending with ab”.</p><div className="guide-grid">{['Contains substring 110','Begins with 1','Ends with 101','Odd number of 0s','Exactly three 0s','Does not contain 00','Even length','Strings over {a,b} containing ab'].map(p=><button className="example" key={p} onClick={()=>setPrompt(p)}>{p}</button>)}</div><p className="muted">Patterns and exact counts: up to 12. Simulation: up to 200 symbols. An empty test input represents ε.</p></section>}
      <section className="input-panel panel"><div className="section-label"><h2><label htmlFor="language-input">Describe your language</label></h2><span className="muted parser-tag">One condition at a time</span></div><form className="prompt-form" onSubmit={generate}><input id="language-input" aria-label="Describe your language" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe the language you want to recognize..."/><button className="primary" type="submit">Generate Automaton</button></form><div className="examples"><span>Try an example</span>{examples.map((p,i)=><button key={p} className="example" onClick={()=>setPrompt(p)}>{['Contains 101','Ends with 01','Starts with 10','Even 1s','Exactly two 1s','No consecutive 1s'][i]}</button>)}</div>{error && <div className="error" role="alert"><strong>Unable to understand</strong><p>{error}</p><p>Try: Strings containing 101 · Strings ending with 01 · Strings with an even number of 1s. Use one supported condition at a time. The previous automaton remains below.</p></div>}</section>
      <section className="understanding" aria-label="Understanding"><div className="understanding-title"><Check size={18} aria-hidden="true"/><span>Understanding</span></div><div><small>Alphabet</small><code>{'{'+dfa.alphabet.join(', ')+'}'}</code></div><div className="condition"><small>Condition / acceptance</small><strong>{c.condition}</strong></div><div><small>Type</small><strong>DFA</strong></div><div><small>States</small><strong>{dfa.states.length}</strong></div></section>
      <div className="workspace"><section className="graph-panel panel"><div className="panel-heading"><div className="section-label"><h2>Automaton</h2><span className="pill">{dfa.minimized?'Minimized DFA':'Generated DFA'}</span></div><button className="quiet" onClick={()=>setLayoutKey(k=>k+1)} title="Reset layout"><RotateCcw size={15} aria-hidden="true"/>Reset layout</button></div><div className="graph"><Graph dfa={dfa} selected={selected} onSelect={setSelected} current={run?active.state:null} active={active} layoutKey={layoutKey}/></div><div className="graph-caption"><span><i className="legend-circle"/> State <i className="legend-circle double"/> Accepting <i className="legend-circle live"/> Current</span><span>Click a state to explore · Drag to arrange</span></div></section>
      <aside className="explanation panel"><div className="section-label"><Info size={17} aria-hidden="true"/><h2>State explanation</h2></div><div className="state-title"><code>{state.id}</code><span className="pill">{dfa.accepting.includes(state.id)?'Accepting':'Non-accepting'}{state.id===dfa.start?' · Start':''}</span></div>{state.members && <p className="muted">Original: {state.members.join(', ')}</p>}<small className="eyebrow">Meaning</small><p>{state.meaning}</p><div className="state-transitions">{dfa.alphabet.map(a=>{const target=dfa.transitions[state.id][a];return <div key={a}><div className="transition-title">On <code>{a}</code><span>→</span><button onClick={()=>setSelected(target)}>{target}</button></div><p>{dfa.states.find(s=>s.id===target).meaning}</p></div>;})}</div></aside></div>
      <div className="lower-grid"><section className="simulation panel"><div className="panel-heading"><div className="section-label"><h2><label htmlFor="test-input">Test your string</label></h2></div><span className="muted">Empty input = ε</span></div><form className="test-form" onSubmit={startSimulation}><input id="test-input" value={input} aria-label="Test string" onChange={e=>{setInput(e.target.value);clearRun();}} placeholder="Enter a string, or leave empty for ε"/><button className="secondary" type="submit"><Play size={16} aria-hidden="true"/>Simulate</button></form>{testError && <div role="alert" className="error">{testError}</div>}
      {run ? <><div className="input-tape" aria-label="Input progress">{run.input.length ? [...run.input].map((a,i)=><span className={i<cursor?'consumed':i===cursor?'next-char':''} key={i}>{a}</span>) : <span>ε</span>}</div><div className="playback"><button className="secondary" onClick={()=>{if(done)setCursor(0);setPlaying(!playing);}}>{playing?<Pause size={15} aria-hidden="true"/>:<Play size={15} aria-hidden="true"/>} {playing?'Pause':'Play'}</button><button className="quiet" disabled={done} onClick={()=>{setPlaying(false);setCursor(c=>Math.min(c+1,run.steps.length-1));}}><StepForward size={16} aria-hidden="true"/>Next</button><button className="quiet" onClick={()=>{setPlaying(false);setCursor(0);}}><RotateCcw size={15} aria-hidden="true"/>Reset</button><span className="muted">{cursor} / {run.input.length} symbols read</span></div><div className="trace">{run.steps.slice(0,cursor+1).map((s,i)=><React.Fragment key={i}>{i>0 && <span className="trace-symbol">{s.symbol} →</span>}<button onClick={()=>setSelected(s.state)} className={i===cursor?'trace-current':''}>{s.state}</button></React.Fragment>)}</div><div className={`result ${done?(run.accepted?'accepted':'rejected'):''}`} role="status">{done ? <>{run.accepted?<Check size={20} aria-hidden="true"/>:<X size={20} aria-hidden="true"/>}<div><strong>{run.accepted?'ACCEPTED':'REJECTED'}</strong><p>The input finished in {run.final}, which {run.accepted?'is':'is not'} an accepting state. {c.acceptance}.</p></div></> : <><span className="pulse"/><div><strong>{playing?'Running simulation':'Simulation paused'}</strong><p>Current state: {active.state}. {cursor<run.input.length?`Next symbol: ${run.input[cursor]}`:'No symbols remain.'}</p></div></>}</div></> : <div className="empty-simulation"><Workflow size={25} aria-hidden="true"/><p>Follow your string, one transition at a time.</p><span>Play the path or step through it yourself.</span></div>}
      </section><section className="table-panel panel"><div className="panel-heading"><div className="section-label"><h2>Transition table</h2></div><span className="muted">δ(q, symbol)</span></div><div className="table-scroll"><table><thead><tr><th>State</th>{dfa.alphabet.map(a=><th key={a}>{a}</th>)}</tr></thead><tbody>{dfa.states.map(s=><tr key={s.id} className={active?.state===s.id?'active-row':''} onClick={()=>setSelected(s.id)}><td><button onClick={()=>setSelected(s.id)}>{s.id===dfa.start?'→ ':''}{dfa.accepting.includes(s.id)?'★ ':''}{s.id}</button></td>{dfa.alphabet.map(a=><td key={a}>{dfa.transitions[s.id][a]}</td>)}</tr>)}</tbody></table></div><p className="table-key">→ Start state &nbsp; ★ Accepting state</p></section></div>
      <section className="minimization panel"><div className="minimize-copy"><div className="section-label"><Minimize2 size={18} aria-hidden="true"/><h2>DFA minimization</h2></div><p>Find the smallest machine with the same language.</p></div>{dfa.minimized && <div className="min-stats"><div><small>Original</small><strong>{original.states.length}</strong></div><div><small>Minimized</small><strong>{dfa.states.length}</strong></div><div><small>Reduced</small><strong>{original.states.length-dfa.states.length}</strong></div></div>}<div className="min-actions">{dfa.minimized && <button className="quiet" onClick={()=>{setDfa(original);setSelected(original.start);clearRun();}}>Show original</button>}<button className="secondary" onClick={minimize}><Minimize2 size={16} aria-hidden="true"/>Minimize DFA</button></div>{dfa.minimized && <p className="min-note">{original.states.length===dfa.states.length?'This DFA is already minimal. ':''}Equivalent states are merged because they have identical acceptance behavior for all possible future inputs. Unreachable states are removed first.</p>}</section>
      <footer><span>AutoMind AI <span className="footer-divider">/</span> Explainable Natural Language-Based Automata Generation and Learning Platform</span><span>Aarav Gupta · 24BIT0245 &nbsp; / &nbsp; Abhishek Yennam · 24BIT0603</span></footer>
    </main></div>;
}
