import React, { useEffect, useState } from 'react';
import { Workflow, Play, Pause, StepForward, RotateCcw, Minimize2, Check, X, Info, BookOpen } from 'lucide-react';
import { parseConstraint, examples } from './core/parser.js';
import { generateDFA, generateNFA, determinizeNFA, transitionTargets, minimizeDFA, simulate } from './core/automata.js';
import Graph from './Graph.jsx';
const initial = generateDFA(parseConstraint(examples[0]));
export default function App() {
  const [prompt,setPrompt]=useState(examples[0]), [original,setOriginal]=useState(initial), [dfa,setDfa]=useState(initial);
  const [error,setError]=useState(''), [selected,setSelected]=useState('q0'), [layoutKey,setLayoutKey]=useState(0);
  const [input,setInput]=useState('110101'), [run,setRun]=useState(null), [cursor,setCursor]=useState(0), [playing,setPlaying]=useState(false), [testError,setTestError]=useState('');
  const [help,setHelp]=useState(false), [generationType,setGenerationType]=useState('DFA'), [conversionError,setConversionError]=useState('');
  const isNFA = dfa.type === 'NFA';
  const displayStates = states => states.length ? `{${states.join(', ')}}` : '∅';
  const tableSymbols = [...dfa.alphabet, ...(dfa.states.some(s => transitionTargets(dfa, s.id, 'ε').length) ? ['ε'] : [])];
  useEffect(()=>{ if (!playing || !run) return; const timer=setInterval(()=>setCursor(c=>Math.min(c+1,run.steps.length-1)),650); return ()=>clearInterval(timer); },[playing,run]);
  useEffect(()=>{if(run && cursor===run.steps.length-1)setPlaying(false);},[cursor,run]);
  function clearRun(){setRun(null);setCursor(0);setPlaying(false);setTestError('');setConversionError('');}
  function generate(e, type=generationType){e?.preventDefault();try{const next=(type==='NFA'?generateNFA:generateDFA)(parseConstraint(prompt));setGenerationType(type);setOriginal(next);setDfa(next);setSelected(next.start);setError('');clearRun();}catch(err){setError(err.message);setPlaying(false);}}
  function startSimulation(e){e?.preventDefault();try{const result=simulate(dfa,input);setRun(result);setCursor(0);setPlaying(result.steps.length>1);setTestError('');setConversionError('');}catch(err){clearRun();setTestError(err.message);}}
  function convert(){try{const next=determinizeNFA(dfa);setOriginal(next);setDfa(next);setSelected(next.start);clearRun();}catch(err){setConversionError(err.message);}}
  function changeType(type){setGenerationType(type);generate(null,type);}
  function minimize(){const next=minimizeDFA(original);setDfa(next);setSelected(next.start);clearRun();}
  const c=dfa.constraint, state=dfa.states.find(s=>s.id===selected), active=run?.steps[cursor], done=run && cursor===run.steps.length-1;
  return <div className="app-shell">
    <a className="skip-link" href="#workspace">Skip to workspace</a><header className="topbar"><a className="brand" href="#"><span className="brand-icon"><Workflow size={23} aria-hidden="true"/></span>AutoMind <span className="brand-ai">AI</span></a><span className="course-label">Automata lab</span><button className="quiet" aria-expanded={help} aria-controls="pattern-guide" onClick={()=>setHelp(!help)}><BookOpen size={17} aria-hidden="true"/> Pattern guide</button></header>
    <main id="workspace">
      <div className="intro"><div><h1>From natural language to automata.</h1><p>Describe a language, explore its states, and follow a string through the machine.</p></div></div>
      {help && <section id="pattern-guide" className="guide panel"><h2>Supported pattern guide</h2><p>Use one condition per description. Binary is the default; a/b patterns infer {'{a, b}'}. Declare an alphabet with “Strings over {'{a,b}'} ending with ab”.</p><div className="guide-grid">{['Contains substring 110','Begins with 1','Ends with 101','Odd number of 0s','Exactly three 0s','Does not contain 00','Even length','Strings over {a,b} containing ab'].map(p=><button className="example" key={p} onClick={()=>setPrompt(p)}>{p}</button>)}</div><p className="muted">Patterns and exact counts: up to 12. Simulation: up to 200 symbols. An empty test input represents ε.</p></section>}
      <section className="input-panel panel"><div className="section-label"><h2><label htmlFor="language-input">Describe your language</label></h2><span className="muted parser-tag">One condition at a time</span></div><div className="type-picker"><span id="automaton-type-label">Create</span><div role="group" aria-labelledby="automaton-type-label" className="segmented-control">{['DFA','NFA'].map(type=><button key={type} type="button" aria-pressed={generationType===type} onClick={()=>changeType(type)}>{type}</button>)}</div><span className="muted">{generationType==='NFA'?'Follow all possible paths':'One transition per symbol'}</span></div><form className="prompt-form" onSubmit={generate}><input id="language-input" aria-label="Describe your language" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Describe the language you want to recognize..."/><button className="primary" type="submit">Generate Automaton</button></form><div className="examples"><span>Try an example</span>{examples.map((p,i)=><button key={p} className="example" onClick={()=>setPrompt(p)}>{['Contains 101','Ends with 01','Starts with 10','Even 1s','Exactly two 1s','No consecutive 1s'][i]}</button>)}</div>{error && <div className="error" role="alert"><strong>Unable to understand</strong><p>{error}</p><p>Try: Strings containing 101 · Strings ending with 01 · Strings with an even number of 1s. Use one supported condition at a time. The previous automaton remains below.</p></div>}</section>
      <section className="understanding" aria-label="Understanding"><div className="understanding-title"><Check size={18} aria-hidden="true"/><span>Understanding</span></div><div><small>Alphabet</small><code>{'{'+dfa.alphabet.join(', ')+'}'}</code></div><div className="condition"><small>Condition / acceptance</small><strong>{c.condition}</strong></div><div><small>Type</small><strong>{dfa.type}</strong></div><div><small>States</small><strong>{dfa.states.length}</strong></div></section>
      {isNFA && <section className="nfa-note panel"><strong>How this NFA works</strong><p>{dfa.construction}</p><p>An input is accepted if at least one branch finishes in an accepting state. ∅ means that no branch survives.</p></section>}<div className="workspace"><section className="graph-panel panel"><div className="panel-heading"><div className="section-label"><h2>Automaton</h2><span className="pill">{dfa.minimized?'Minimized DFA':dfa.converted?'Converted DFA':`Generated ${dfa.type}`}</span></div><button className="quiet" onClick={()=>setLayoutKey(k=>k+1)} title="Reset layout"><RotateCcw size={15} aria-hidden="true"/>Reset layout</button></div><div className="graph"><Graph dfa={dfa} selected={selected} onSelect={setSelected} current={run?active.states:[]} active={active} layoutKey={layoutKey}/></div><div className="graph-caption"><span><i className="legend-circle"/> State <i className="legend-circle double"/> Accepting <i className="legend-circle live"/> {isNFA?'Active':'Current'}</span><span>Click a state to explore · Drag to arrange</span></div></section>
      <aside className="explanation panel"><div className="section-label"><Info size={17} aria-hidden="true"/><h2>State explanation</h2></div><div className="state-title"><code>{state.id}</code><span className="pill">{dfa.accepting.includes(state.id)?'Accepting':'Non-accepting'}{state.id===dfa.start?' · Start':''}</span></div>{state.members && <p className="muted">Original: {state.members.join(', ')}</p>}<small className="eyebrow">Meaning</small><p>{state.meaning}</p><div className="state-transitions">{tableSymbols.map(a=>{const targets=transitionTargets(dfa,state.id,a);return <div key={a}><div className="transition-title">On <code>{a}</code><span>→</span>{targets.length?targets.map(target=><button key={target} onClick={()=>setSelected(target)}>{target}</button>):<code>∅</code>}</div><p>{targets.length>1?`This symbol branches to ${targets.join(' and ')}. The simulator follows all of these states.`:targets.length && targets[0]===state.id?`Remain in ${state.id}; this symbol does not change what the state represents.`:targets.length?dfa.states.find(s=>s.id===targets[0]).meaning:'No transition exists for this symbol. This branch ends.'}</p></div>;})}</div></aside></div>
      <div className="lower-grid"><section className="simulation panel"><div className="panel-heading"><div className="section-label"><h2><label htmlFor="test-input">Test your string</label></h2></div><span className="muted">Empty input = ε</span></div><form className="test-form" onSubmit={startSimulation}><input id="test-input" value={input} aria-label="Test string" onChange={e=>{setInput(e.target.value);clearRun();}} placeholder="Enter a string, or leave empty for ε"/><button className="secondary" type="submit"><Play size={16} aria-hidden="true"/>Simulate</button></form>{testError && <div role="alert" className="error">{testError}</div>}
      {run ? <><div className="input-tape" aria-label="Input progress">{run.input.length ? [...run.input].map((a,i)=><span className={i<cursor?'consumed':i===cursor?'next-char':''} key={i}>{a}</span>) : <span>ε</span>}</div><div className="playback"><button className="secondary" onClick={()=>{if(done)setCursor(0);setPlaying(!playing);}}>{playing?<Pause size={15} aria-hidden="true"/>:<Play size={15} aria-hidden="true"/>} {playing?'Pause':'Play'}</button><button className="quiet" disabled={done} onClick={()=>{setPlaying(false);setCursor(c=>Math.min(c+1,run.steps.length-1));}}><StepForward size={16} aria-hidden="true"/>Next</button><button className="quiet" onClick={()=>{setPlaying(false);setCursor(0);}}><RotateCcw size={15} aria-hidden="true"/>Reset</button><span className="muted">{cursor} / {run.input.length} symbols read</span></div><div className="trace">{run.steps.slice(0,cursor+1).map((s,i)=><React.Fragment key={i}>{i>0 && <span className="trace-symbol">{s.symbol} →</span>}<div className={`trace-group ${i===cursor?'trace-current-group':''}`}>{isNFA && <span>{s.states.length?'\u007b':'∅'}</span>}{s.states.map((q,j)=><React.Fragment key={q}>{isNFA && j>0 && <span>,</span>}<button onClick={()=>setSelected(q)} className={i===cursor?'trace-current':''}>{q}</button></React.Fragment>)}{isNFA && s.states.length>0 && <span>{'\u007d'}</span>}</div></React.Fragment>)}</div><div className={`result ${done?(run.accepted?'accepted':'rejected'):''}`} role="status">{done ? <>{run.accepted?<Check size={20} aria-hidden="true"/>:<X size={20} aria-hidden="true"/>}<div><strong>{run.accepted?'ACCEPTED':'REJECTED'}</strong><p>{isNFA ? `Final active states: ${displayStates(run.finalStates)}. ${run.accepted?'At least one active state is accepting.':'No active state is accepting.'}` : `The input finished in ${run.final}, which ${run.accepted?'is':'is not'} an accepting state.`} {c.acceptance}.</p></div></> : <><span className="pulse"/><div><strong>{playing?'Running simulation':'Simulation paused'}</strong><p>{isNFA?'Active states':'Current state'}: {isNFA?displayStates(active.states):active.state}. {cursor<run.input.length?`Next symbol: ${run.input[cursor]}`:'No symbols remain.'}</p></div></>}</div></> : <div className="empty-simulation"><Workflow size={25} aria-hidden="true"/><p>Follow your string, one transition at a time.</p><span>Play the path or step through it yourself.</span></div>}
      </section><section className="table-panel panel"><div className="panel-heading"><div className="section-label"><h2>Transition table</h2></div><span className="muted">δ(q, symbol)</span></div><div className="table-scroll"><table><thead><tr><th>State</th>{tableSymbols.map(a=><th key={a}>{a}</th>)}</tr></thead><tbody>{dfa.states.map(s=><tr key={s.id} className={active?.states.includes(s.id)?'active-row':''} onClick={()=>setSelected(s.id)}><td><button onClick={()=>setSelected(s.id)}>{s.id===dfa.start?'→ ':''}{dfa.accepting.includes(s.id)?'★ ':''}{s.id}</button></td>{tableSymbols.map(a=><td key={a}>{isNFA?displayStates(transitionTargets(dfa,s.id,a)):dfa.transitions[s.id][a]}</td>)}</tr>)}</tbody></table></div><p className="table-key">{isNFA && <>Each cell is a destination set. ∅ = no transition.<br/></>}→ Start state &nbsp; ★ Accepting state</p></section></div>
      <section className="minimization panel"><div className="minimize-copy"><div className="section-label"><Minimize2 size={18} aria-hidden="true"/><h2>{isNFA?'NFA to DFA':'DFA minimization'}</h2></div><p>{isNFA?'Convert active-state sets into DFA states, then minimize.':'Find the smallest machine with the same language.'}</p></div>{dfa.minimized && <div className="min-stats"><div><small>Original</small><strong>{original.states.length}</strong></div><div><small>Minimized</small><strong>{dfa.states.length}</strong></div><div><small>Reduced</small><strong>{original.states.length-dfa.states.length}</strong></div></div>}<div className="min-actions">{dfa.minimized && <button className="quiet" onClick={()=>{setDfa(original);setSelected(original.start);clearRun();}}>Show original</button>}<button className="secondary" onClick={isNFA?convert:minimize}><Minimize2 size={16} aria-hidden="true"/>{isNFA?'Convert to DFA':'Minimize DFA'}</button></div>{conversionError && <div className="error" role="alert">{conversionError}</div>}{dfa.converted && !dfa.minimized && <p className="min-note">Converted by subset construction: {dfa.sourceCount} NFA states become {dfa.states.length} reachable DFA states. Select a state to see its NFA members.</p>}{dfa.minimized && <p className="min-note">{original.states.length===dfa.states.length?'This DFA is already minimal. ':''}Equivalent states are merged because they have identical acceptance behavior for all possible future inputs. Unreachable states are removed first.</p>}</section>
      <footer><span>AutoMind AI <span className="footer-divider">/</span> Explainable Natural Language-Based Automata Generation and Learning Platform</span><span>Aarav Gupta · 24BIT0245 &nbsp; / &nbsp; Abhishek Yennam · 24BIT0603</span></footer>
    </main></div>;
}
